from __future__ import annotations

import base64
import json

import pytest

from crypted_mail.core.crypto import CryptoService
from crypted_mail.core.envelope import (
    ARMORED_FOOTER,
    ARMORED_HEADER,
    COMPACT_PREFIX,
    PUBLIC_KEY_MODE,
    SHARED_PASSPHRASE_MODE,
    build_email_body,
)
from crypted_mail.core.exceptions import EnvelopeError, KeyProtectionError
from crypted_mail.services.key_service import KeyService
from crypted_mail.services.storage import AppRepository


def test_model_a_round_trip():
    crypto = CryptoService()
    armored = crypto.encrypt_with_passphrase(
        "hello secure world",
        "correct horse battery staple",
        sender_hint="alice@example.com",
        note="Use the passphrase we agreed on by phone.",
    )
    plaintext = crypto.decrypt_with_passphrase(armored, "correct horse battery staple")
    envelope = crypto.parse_message(armored)

    assert plaintext == "hello secure world"
    assert envelope.mode == SHARED_PASSPHRASE_MODE
    assert envelope.note == "Use the passphrase we agreed on by phone."
    assert armored.startswith(COMPACT_PREFIX)


def test_wrong_shared_passphrase_is_rejected():
    crypto = CryptoService()
    armored = crypto.encrypt_with_passphrase("secret", "correct passphrase")

    with pytest.raises(EnvelopeError):
        crypto.decrypt_with_passphrase(armored, "wrong passphrase")


def test_legacy_public_key_round_trip(key_service):
    profile = key_service.create_profile("Alice", "alice@example.com", "profile passphrase")
    recipient = key_service.import_recipient(key_service.export_public_key())
    crypto = CryptoService()

    armored = crypto.encrypt_for_recipient("legacy text", recipient, sender_hint="alice@example.com")
    plaintext = crypto.decrypt_message(armored, profile, "profile passphrase")
    envelope = crypto.parse_message(armored)

    assert plaintext == "legacy text"
    assert envelope.mode == PUBLIC_KEY_MODE


def test_legacy_messages_without_mode_still_parse(key_service):
    profile = key_service.create_profile("Alice", "alice@example.com", "passphrase")
    recipient = key_service.import_recipient(key_service.export_public_key())
    crypto = CryptoService()
    current = crypto.parse_message(crypto.encrypt_for_recipient("legacy", recipient))

    legacy_payload = {
        "version": current.version,
        "algorithm": current.algorithm,
        "recipient_key_id": current.recipient_key_id,
        "created_at": current.created_at,
        "ciphertext_b64": current.ciphertext_b64,
        "sender_hint": current.sender_hint,
        "note": current.note,
    }
    encoded = base64.b64encode(json.dumps(legacy_payload).encode("utf-8")).decode("ascii")
    legacy_armored = f"{ARMORED_HEADER}\n{encoded}\n{ARMORED_FOOTER}"

    plaintext = crypto.decrypt_message(legacy_armored, profile, "passphrase")
    parsed = crypto.parse_message(legacy_armored)
    assert plaintext == "legacy"
    assert parsed.mode == PUBLIC_KEY_MODE


def test_email_body_contains_optional_note():
    body = build_email_body("ciphertext", note="Use the passphrase from Signal.")
    assert "Use the passphrase from Signal." in body
    assert "ciphertext" in body
    assert "generated by Crypted Mail" not in body


def test_wrong_profile_passphrase_still_raises(key_service):
    profile = key_service.create_profile("Alice", "alice@example.com", "correct passphrase")
    recipient = key_service.import_recipient(key_service.export_public_key())
    crypto = CryptoService()
    armored = crypto.encrypt_for_recipient("secret", recipient)

    with pytest.raises(KeyProtectionError):
        crypto.decrypt_message(armored, profile, "wrong passphrase")


def test_wrong_recipient_rejected(app_paths):
    alice_repo = AppRepository(paths=app_paths)
    alice_keys = KeyService(alice_repo)
    alice_keys.create_profile("Alice", "alice@example.com", "alice passphrase")
    alice_recipient = alice_keys.import_recipient(alice_keys.export_public_key())

    bob_paths = app_paths.__class__(
        base_dir=app_paths.base_dir / "bob",
        state_file=app_paths.base_dir / "bob" / "state.json",
        profile_file=app_paths.base_dir / "bob" / "profile.json",
        recipients_file=app_paths.base_dir / "bob" / "recipients.json",
        token_cache_file=app_paths.base_dir / "bob" / "tokens.json",
    )
    bob_repo = AppRepository(paths=bob_paths)
    bob_keys = KeyService(bob_repo)
    bob = bob_keys.create_profile("Bob", "bob@example.com", "bob passphrase")

    crypto = CryptoService()
    armored = crypto.encrypt_for_recipient("secret", alice_recipient)

    with pytest.raises(EnvelopeError):
        crypto.decrypt_message(armored, bob, "bob passphrase")
