from __future__ import annotations

import base64
import json

import pytest

from crypted_mail import CryptedMailClient
from crypted_mail.core.crypto import CryptoService
from crypted_mail.core.envelope import COMPACT_PREFIX, SHARED_PASSPHRASE_MODE, build_email_body
from crypted_mail.core.exceptions import EnvelopeError


def test_model_a_round_trip():
    crypto = CryptoService()
    armored = crypto.encrypt_with_passphrase(
        "hello secure world",
        "correct horse battery staple",
        sender_hint="alice@example.com",
        note="Use the passphrase we agreed on by phone.",
    )
    plaintext = crypto.decrypt_with_passphrase(armored, "correct horse battery staple")
    envelope = crypto.parse_message(armored)

    assert plaintext == "hello secure world"
    assert envelope.mode == SHARED_PASSPHRASE_MODE
    assert envelope.note == "Use the passphrase we agreed on by phone."
    assert armored.startswith(COMPACT_PREFIX)


def test_wrong_shared_passphrase_is_rejected():
    crypto = CryptoService()
    armored = crypto.encrypt_with_passphrase("secret", "correct passphrase")

    with pytest.raises(EnvelopeError):
        crypto.decrypt_with_passphrase(armored, "wrong passphrase")


def test_message_missing_mode_is_rejected():
    payload = {
        "version": 1,
        "algorithm": "argon2id-xsalsa20poly1305-secretbox",
        "created_at": "2026-03-22T12:00:00+00:00",
        "ciphertext_b64": base64.b64encode(b"ciphertext").decode("ascii"),
        "salt_b64": base64.b64encode(b"1234567890123456").decode("ascii"),
        "nonce_b64": base64.b64encode(b"123456789012345678901234").decode("ascii"),
    }
    encoded = base64.b64encode(json.dumps(payload).encode("utf-8")).decode("ascii")

    with pytest.raises(EnvelopeError):
        CryptoService().parse_message(f"{COMPACT_PREFIX}{encoded}")


def test_email_body_contains_optional_note():
    body = build_email_body("ciphertext", note="Use the passphrase from Signal.")
    assert "Use the passphrase from Signal." in body
    assert "ciphertext" in body
    assert "generated by Crypted Mail" not in body


def test_client_encrypt_and_send_with_passphrase(monkeypatch):
    client = CryptedMailClient()
    captured = {}

    def fake_send_encrypted_email(
        sender: str,
        recipient_email: str,
        subject: str,
        armored_payload: str,
        credentials_or_token: str,
    ) -> str:
        captured["sender"] = sender
        captured["recipient_email"] = recipient_email
        captured["subject"] = subject
        captured["armored_payload"] = armored_payload
        captured["credentials_or_token"] = credentials_or_token
        return "gmail-message-123"

    monkeypatch.setattr(client, "send_encrypted_email", fake_send_encrypted_email)

    message_id = client.encrypt_and_send_with_passphrase(
        sender="alice@example.com",
        recipient_email="bob@example.com",
        subject="Encrypted",
        plaintext="hello secure world",
        passphrase="correct horse battery staple",
        credentials_or_token="serialized-creds",
        sender_hint="alice@example.com",
        note="Use the passphrase we agreed on by phone.",
    )

    assert message_id == "gmail-message-123"
    assert captured["sender"] == "alice@example.com"
    assert captured["recipient_email"] == "bob@example.com"
    assert captured["subject"] == "Encrypted"
    assert captured["credentials_or_token"] == "serialized-creds"
    assert captured["armored_payload"].startswith(COMPACT_PREFIX)
